---
title: "Data visualization final project"
author: "Sungil Park"
date: "2023/06/10"
date-modified: "2023/06/10"
description: "data visualization final project"
categories: R
editor_options: 
  chunk_output_type: inline
---

# 한남대 주변 버스정류장 승차 데이터 시각화

[link](https://sungileo.github.io/sanai_sungil/posts/vis_final/data_visualizing_final.html)

```{r, include=FALSE}
rm(list=ls())
library(tidyverse)
```

```{r, include=FALSE}
daejeon_bus <- read.csv("https://raw.githubusercontent.com/Sungileo/trainsets_2/main/daejeon_bus_2.csv",sep = "|")

st_2 <- read.csv("C:/trainsets_2/station-info_4.txt",sep = "|")

st_2 <- st_2 %>% select(BUS_NODE_ID,BUS_NODE_NM)
names(st_2)[1] <- "BUS_STTN_ID"

st_3 <- daejeon_bus %>% select(HH_ID,BUS_ROUTE_ID,BUS_STTN_ID,GETON_CNT,GETOFF_CNT,TRANSF_PSNGR_CNT)

data_2 <- st_3 %>% left_join(st_2,by = "BUS_STTN_ID")


data_3 <- data_2 %>% filter(BUS_NODE_NM %in% c("한남대학교","한남로삼거리","한숲아파트","한남대북문","대전신학대학교"))

```

## 목적

-   한남대 주변 버스정류장의 시간대별 사용량을 알아봄으로서 버스의 유연한 배차 기획

## 데이터

국가교통 데이터 오픈마켓

-   [**대전시 대중교통 이용정보 데이터**](https://www.bigdata-transportation.kr/frn/prdt/detail?prdtId=PRDTNUM_000000000243)

-   [**대전시 버스 정류장 속성 데이터**](https://www.bigdata-transportation.kr/frn/prdt/detail?prdtId=PRDTNUM_000000000166)

```{mermaid}
graph RL
    A[버스 정류장 속성<br> - 버스정류장 코드<br> - 버스정류장 이름<br> - ..] -->|버스정류장 코드| B[버스 이용량<br>  - 노선번호 <br> - 정류장 코드 <br> - 탑승객수<br> - 하차승객수<br> - ..]
```

## 정류장, 노선별

### 한남로삼거리

```{r, echo=FALSE}

data_3 %>% 
  filter(BUS_NODE_NM == "한남로삼거리") %>% 
  group_by(HH_ID,BUS_ROUTE_ID) %>% 
  summarize(cnt = sum(GETON_CNT), .groups = "drop") %>% 
  ggplot(aes(x=HH_ID,y=factor(BUS_ROUTE_ID),fill=cnt))+
  geom_tile(width = .95,height = 0.95)+
  coord_fixed(expand = FALSE)+
  scale_fill_viridis_c(option = "B",
                       begin = 0.15, 
                       end = 0.99,
                       name = "시간대별 승차인원 (명)",
                       direction = -1)+
  labs(title = "한남로삼거리")+
  scale_y_discrete(name = "노선번호",label = c("105","314","711"))+
  scale_x_continuous(name = "시간대",
                     breaks = c(5:23))+
  theme(plot.margin = margin(0, 0, 0, 0))
```

### 한남대학교

```{r, echo=FALSE}
data_3 %>% 
  filter(BUS_NODE_NM == "한남대학교" &
           BUS_ROUTE_ID != 30300065) %>% 
  group_by(HH_ID,BUS_ROUTE_ID) %>% 
  summarize(cnt = sum(GETON_CNT), .groups = "drop") %>% 
  ggplot(aes(x=HH_ID,y=factor(BUS_ROUTE_ID),fill=cnt))+
  geom_tile(width = .95,height = 0.95)+
  coord_fixed(expand = FALSE)+
  scale_fill_viridis_c(option = "B",
                       begin = 0.15, 
                       end = 0.99,
                       name = "시간대별 승차인원 (명)",
                       direction = -1)+
  labs(title = "한남대학교")+
  scale_y_discrete(name = "노선번호",label = c("105","314","711"))+
  scale_x_continuous(name = "시간대",
                     breaks = c(6:23))+
  theme(plot.margin = margin(0, 0, 0, 0))
```

### 한남대북문

```{r, echo=FALSE}
data_3 %>% 
  filter(BUS_NODE_NM == "한남대북문") %>% 
  group_by(HH_ID,BUS_ROUTE_ID) %>% 
  summarize(cnt = sum(GETON_CNT), .groups = "drop") %>% 
  ggplot(aes(x=HH_ID,y=factor(BUS_ROUTE_ID),fill=cnt))+
  geom_tile(width = .95,height = 0.95)+
  coord_fixed(expand = FALSE)+
  scale_fill_viridis_c(option = "B",
                       begin = 0.15, 
                       end = 0.99,
                       name = "시간대별 승차인원 (명)",
                       direction = -1)+
  labs(title = "한남대북문")+
  scale_y_discrete(name = "노선번호",
                   label = c("102","605","611","706","802"))+
  scale_x_continuous(name = "시간대",
                     breaks = c(5:23))+
  theme(plot.margin = margin(0, 0, 0, 0))
```

### 한숲아파트

```{r, echo=FALSE}
data_3 %>% 
  filter(BUS_NODE_NM == "한숲아파트") %>% 
  group_by(HH_ID,BUS_ROUTE_ID) %>% 
  summarize(cnt = sum(GETON_CNT), .groups = "drop") %>% 
  ggplot(aes(x=HH_ID,y=factor(BUS_ROUTE_ID),fill=cnt))+
  geom_tile(width = .95,height = 0.95)+
  coord_fixed(expand = FALSE)+
  scale_fill_viridis_c(option = "B",
                       begin = 0.15, 
                       end = 0.99,
                       name = "시간대별 승차인원 (명)",
                       direction = -1)+
  scale_y_discrete(name = "노선번호",
                   label = c("314","711"))+
  scale_x_continuous(name = "시간대",
                     breaks = c(5:22))+
  labs(title = "한숲아파트")+
  theme(plot.margin = margin(0, 0, 0, 0))


```

## 정류장별 승차인원

```{r,echo=FALSE}
data_3 %>% 
  group_by(BUS_NODE_NM,HH_ID) %>% 
  summarize(cnt=sum(GETON_CNT),.groups = "drop") %>% 
  filter(BUS_NODE_NM %in% c("한남로삼거리","한숲아파트","한남대북문")) %>% 
  ggplot(aes(x=HH_ID,y=BUS_NODE_NM,fill=cnt))+
  geom_tile(width = .95,height = 0.95)+
  coord_fixed(expand = FALSE)+
  scale_fill_viridis_c(option = "B",
                       begin = 0.15, 
                       end = 0.99,
                       name = "시간대별 승차인원 (명)",
                       direction = -1)+
  scale_x_continuous(name = "시간대",
                     breaks = c(5:23))+
  scale_y_discrete(name = "정류장")
```

## 한계점

-   시간대별 버스 이용량보다 작은 단위로 시각화 필요

-   학생이 주 사용자기 때문에 방학시기는 따로 고려해야함


