---
title: "Geocomputation Apply"
author: "sungil_park"
date: "2023/04/29"
date-modified: "2023/04/29"
description: "Geocomputation"
categories: R
editor_options: 
  chunk_output_type: inline
---

```{r}
#| warning: false
#| message: false
```

## Library packages

```{r}
rm(list = ls())

library(sf)
library(tidyverse)
library(rgdal)
library(plotly)
library(ggtext)
library(tmap)
```

## Load data

Following data is geographic data for Chungcheongnam-do.

http://data.nsdi.go.kr/dataset/15145

| EMD_CD      | EMD_NM      | SGG_OID     | COL_ADM_SE | GID | geometry |
|-------------|-------------|-------------|------------|-----|----------|
| 읍면동 코드 | 읍면동 이름 | 시군구 코드 | 시 코드    | GID | 지리정보 |

Convert data type (`sp` -\> `sf`)

```{r}
data_sp <- readOGR("C:/trainsets_2/LSMD_ADM_SECT_UMD_충남/LSMD_ADM_SECT_UMD_44.shp",encoding = "euc-kr")

data_sf = st_as_sf(data_sp)
data_sf %>% head()
```

```{r}
data_sf %>% ggplot(aes(fill = COL_ADM_SE))+
  geom_sf()+
  theme_minimal()+
  labs(title = "충청남도")
```

## Filter Place of Interest

```{r}
cheonan <- data_sf %>% 
  filter(COL_ADM_SE=="44130")

cheonan_seobuk <- cheonan %>%  
  filter(substr(EMD_CD,1,5)=="44133")

cheonan_dongnam <- cheonan %>%  
  filter(substr(EMD_CD,1,5)=="44131")
```

```{r}
cheonan %>% ggplot(aes(fill=substr(EMD_CD,1,5)))+
  geom_sf()+
  theme_minimal()+
  labs(title = "천안시 (구별)")+
  scale_fill_discrete(name = "구",
                      labels = c("동남구","서북구"))
```

```{r}
chsb <- cheonan_seobuk %>% ggplot(aes(fill=EMD_NM))+
  geom_sf()+
  geom_sf_text(mapping = aes(label = EMD_NM))+
  labs(title = "천안시 서북구 (읍면동)")+
  theme_minimal()+
  scale_fill_discrete(name = "읍면동")

chsb %>% ggplotly()
```

```{r}
chdn <- cheonan_dongnam %>% ggplot(aes(fill=EMD_NM))+
  geom_sf()+
  geom_sf_text(mapping = aes(label = EMD_NM))+
  labs(title = "천안시 동남구 (읍면동)")+
  theme_minimal()+
  scale_fill_discrete(name = "읍면동")

chdn %>% ggplotly()
```

## 건축년도

```{r}
data <- read.csv("C:/trainsets_2/GEOCOMPS.csv")
data_sf <- data %>% st_as_sf(coords = c("Longitude","Latitude"))
st_crs(data_sf) <- 4737
st_crs(data_sf)

cheonan <- cheonan %>% 
  filter(EMD_NM!="광덕면")

gn <- ggplot()+
  geom_sf(data = cheonan,fill=NA)+
  geom_sf(data = data_sf,mapping = aes(color = 건축년도))+
  scale_color_gradient(low = "blue", high = "red")+
  theme_minimal()

gn %>% ggplotly()
```

## 아파트별 평단가

### ggplotly

```{r}
data_nm_raw <- read.csv("C:/Users/sungi/Documents/linear_model_dataset_R.csv")
data_nm_raw <- data_nm_raw %>% mutate(평단가 = 거래금액/전용면적)

data_nm <- data_nm_raw %>% 
  group_by(아파트) %>% 
  summarize(평균거래액 = mean(평단가) %>% as.integer(),
            Latitude = mean(Latitude),
            Longitude = mean(Longitude)) %>% 
  mutate(정보 = paste(아파트,평균거래액,sep = ", 평단가 :"))

data_nm_sf <- data_nm %>% st_as_sf(coords = c("Longitude","Latitude"))
st_crs(data_nm_sf) <- 4737

cheonan <- cheonan %>% 
  filter(EMD_NM!="광덕면")

  
gn <- ggplot()+
  geom_sf(data = cheonan,color = "black")+
  geom_sf(data = data_nm_sf,aes(fill = 정보))+
  theme_minimal()+
  theme(legend.position = "none")

gn %>% ggplotly()
```

### Tmap library

```{r}
tmap_mode("view")
tmap_options(check.and.fix = TRUE)

tm_shape(cheonan["EMD_NM"])+
  tm_polygons(col="white",alpha = 0.3)+
  tm_shape(data_nm_sf)+
  tm_symbols(shape = 2, col = "red", size = 0.05)+
  tm_layout(main.title = "High points in New Zealand", main.title.size = 1,
            bg.color = "lightblue")
```


















